language: erlang
os:
  - linux
  - osx
osx_image: xcode8.1	
otp_release:
  - 19.1
  - 19.0
  # - 18.1
  # - 18.0
  # - 17.5
  # - 17.0
  # - R16B03

matrix:
  allow_failures:
    - os: osx
  include:
    - os: osx
      before_script:
        - brew update
before_script:
  - "erl -make"
  - "chmod 777 test.sh"
script: "./test.sh"